version: "3"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./services/gateway/dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./services/gateway:/usr/app/src/services/gateway
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
